In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Intro to pandas Data Structures

## Series

In [30]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [10]:
obj3_dict = obj3.to_dict()
obj3_dict

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [12]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.concat((Series(obj4.isna()), Series(obj4.notna())), axis=1)

0      1
California   True  False
Ohio        False   True
Oregon      False   True
Texas       False   True

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = "Population"
obj4.index.name = "State"
obj4

State
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Population, dtype: float64

In [31]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

In [175]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [176]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [177]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [178]:
frame2_state_series = frame2.state
frame2_state_series[-1:]

5    Nevada
Name: state, dtype: object

In [179]:
frame2.index

RangeIndex(start=0, stop=6, step=1)

In [180]:
frame2.shape

(6, 4)

In [181]:
frame2.state   # frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [182]:
frame2.iloc[1:2]

year state  pop debt
1  2001  Ohio  1.7  NaN

In [183]:
type(frame2.iloc[1:2])

pandas.core.frame.DataFrame

In [184]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [185]:
type(frame2.iloc[1])

pandas.core.series.Series

In [186]:
frame2["debt"] = [float(x) for x in list(range(6))]

In [187]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [188]:
frame2["eastern"] = frame2.state == "Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [189]:
display(frame2)

year   state  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [190]:
del frame2["eastern"]
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [202]:
frame2["debt"][2] = 2.6
frame2

C:\Users\phil7\AppData\Local\Temp\ipykernel_29724\229633071.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2["debt"][2] = 2.6


year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.6
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   3.3

In [201]:
frame2.loc[5, "debt"] = 3.3
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.6
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   3.3

In [193]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}} 

In [194]:
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [210]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [203]:
frame3["Ohio"][-2:]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [208]:
pdata = {"Ohio": frame3["Ohio"][1:],
         "Nevada": frame3["Nevada"][1:]}

In [209]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [211]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [212]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [213]:
frame3.values

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [217]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, 0.0],
       [2001, 'Ohio', 1.7, 1.0],
       [2002, 'Ohio', 3.6, 2.6],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0],
       [2003, 'Nevada', 3.2, 3.3]], dtype=object)

## Index Objects

In [219]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int32

In [223]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [224]:
type(obj.index)

pandas.core.indexes.base.Index

In [225]:
obj.index.name

In [227]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int32')

In [248]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [249]:
obj2.index == labels

array([ True,  True,  True])

In [253]:
obj2.index is labels

True

In [251]:
np.arange(3) is labels

False

In [252]:
np.arange(3) == labels

array([ True,  True,  True])

In [255]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [257]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [258]:
"Ohio" in frame3.columns

True

In [259]:
2003 in frame3.index

False

In [262]:
frame3.index.isin({2001, 2004})

array([False,  True, False])

In [261]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

# Essential Functionality

## Reindexing

In [263]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [264]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [266]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [270]:
frame4 = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                        index=["a", "c", "d"],
                        columns=["Ohio", "Texas", "California"])
frame4

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [272]:
frame4.reindex(index = ['a', 'b', 'c', 'd'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [273]:
frame4.reindex(index = ['a', 'b', 'c', 'd'], columns=["Ohio", "Texas", "Utah", "California"])

Ohio  Texas  Utah  California
a   0.0    1.0   NaN         2.0
b   NaN    NaN   NaN         NaN
c   3.0    4.0   NaN         5.0
d   6.0    7.0   NaN         8.0

In [276]:
frame4.loc[["a", "c", "d"], ["Texas", "California"]]

Texas  California
a      1           2
c      4           5
d      7           8

## Dropping Entries from an Axis

In [277]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [278]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [287]:
obj.drop("c", inplace=True)

In [288]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [279]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [281]:
data.drop(index=["Ohio", "Colorado"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [282]:
data.drop(columns=["one", "two"])

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [283]:
data.drop(index=["Ohio", "Colorado"], columns=["one", "two"])

three  four
Utah         10    11
New York     14    15

In [285]:
data.drop(index=["Ohio", "Colorado"], columns=["one", "two"], inplace=True)

## Indexing, Selection & Filtering

### Series

In [289]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [290]:
obj["b"]

1.0

In [291]:
obj[1]

C:\Users\phil7\AppData\Local\Temp\ipykernel_29724\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [294]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [298]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [296]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [299]:
obj.loc["b"]

1.0

In [300]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [301]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [302]:
obj.iloc[[0,2]]

a    0.0
c    2.0
dtype: float64

In [303]:
obj.loc["b":"c"]

b    1.0
c    2.0
dtype: float64

In [307]:
obj.loc[["a", "b", "d"]]

a    0.0
b    1.0
d    3.0
dtype: float64

### DataFrame

In [343]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [344]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [345]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [346]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [347]:
data[:1]

one  two  three  four
Ohio    0    1      2     3

In [348]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [349]:
data["three"]

Ohio         0
Colorado     6
Utah        10
New York    14
Name: three, dtype: int32

In [350]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [351]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int32

In [352]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [355]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [356]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [357]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [358]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [359]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [360]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [361]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [362]:
data.iloc[:, :3][data.three > 5][data.two > 5]

C:\Users\phil7\AppData\Local\Temp\ipykernel_29724\3923940751.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data.iloc[:, :3][data.three > 5][data.two > 5]


one  two  three
Utah        8    9     10
New York   12   13     14

In [376]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [378]:
data[data.three > 5][data.one < 9]

C:\Users\phil7\AppData\Local\Temp\ipykernel_29724\1413828230.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data.three > 5][data.one < 9]


one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [379]:
data.loc[data.three > 5, ["one", "two"]]

one  two
Colorado    0    5
Utah        8    9
New York   12   13

In [384]:
data.loc[data.three > 5, ["one", "two"]]

one  two
Colorado    0    5
Utah        8    9
New York   12   13

In [382]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## Arithmetic and Data Alignment

In [3]:
s1 = pd.Series([7.3, -2.5,a 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [4]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [8]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [9]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [10]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [7]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [13]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [14]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [15]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [17]:
series3 = frame["d"]
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [18]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [19]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [3]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"]) 
frame

b         d         e
Utah   -1.536146 -2.125659  1.417579
Ohio    0.793884  0.375014 -0.536159
Texas   0.751850 -1.437183  0.625109
Oregon -0.081450  0.072393  0.111652

In [4]:
np.abs(frame)

b         d         e
Utah    1.536146  2.125659  1.417579
Ohio    0.793884  0.375014  0.536159
Texas   0.751850  1.437183  0.625109
Oregon  0.081450  0.072393  0.111652

In [32]:
def f1(x):
    return x.max() - x.min()
frame.apply(f1)

b    2.330030
d    2.500673
e    1.953738
dtype: float64

In [5]:
frame.apply(lambda x: x.max() - x.min())

b    2.330030
d    2.500673
e    1.953738
dtype: float64

In [6]:
frame.apply(lambda x: x.max() - x.min(), axis="columns")

Utah      3.543238
Ohio      1.330042
Texas     2.189032
Oregon    0.193102
dtype: float64

In [7]:
def f2(x: pd.Series) -> pd.Series:
    return pd.Series([x.min(), x.max(), x.max()-x.min()], index=("min", "max", "range"))

In [8]:
frame.apply(f2, axis="columns")

min       max     range
Utah   -2.125659  1.417579  3.543238
Ohio   -0.536159  0.793884  1.330042
Texas  -1.437183  0.751850  2.189032
Oregon -0.081450  0.111652  0.193102

In [9]:
frame.T.apply(f2)

Utah      Ohio     Texas    Oregon
min   -2.125659 -0.536159 -1.437183 -0.081450
max    1.417579  0.793884  0.751850  0.111652
range  3.543238  1.330042  2.189032  0.193102

In [14]:
frame.loc["Utah","b"]

-1.536146457437929

In [16]:
frame.T.max() - frame.T.min()

Utah      3.543238
Ohio      1.330042
Texas     2.189032
Oregon    0.193102
dtype: float64

In [17]:
frame.T.sum()

Utah     -2.244226
Ohio      0.632739
Texas    -0.060224
Oregon    0.102595
dtype: float64

In [24]:
frame.T.abs().sum()

Utah      5.079384
Ohio      1.705056
Texas     2.814142
Oregon    0.265494
dtype: float64

In [28]:
def myformat(x):
    return f"{x:.3f}"
frame.applymap(myformat)

C:\Users\phil7\AppData\Local\Temp\ipykernel_29964\3492559700.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(myformat)


b       d       e
Utah    -1.536  -2.126   1.418
Ohio     0.794   0.375  -0.536
Texas    0.752  -1.437   0.625
Oregon  -0.081   0.072   0.112

In [29]:
frame["e"].map(myformat)

Utah       1.418
Ohio      -0.536
Texas      0.625
Oregon     0.112
Name: e, dtype: object

In [31]:
frame.map(lambda x: f"{x:.3f}")

b       d       e
Utah    -1.536  -2.126   1.418
Ohio     0.794   0.375  -0.536
Texas    0.752  -1.437   0.625
Oregon  -0.081   0.072   0.112

## Sorting and Ranking

In [33]:
obj = pd.Series(range(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [34]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [42]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=["three", "one"], 
                     columns=["d", "a", "b", "c"])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [43]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [44]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [45]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [46]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [47]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [48]:
obj.sort_values(na_position="first")

2   -3
3    2
0    4
1    7
dtype: int64

In [49]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [54]:
frame.sort_values("a")

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [53]:
frame.sort_values(by=["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [104]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [105]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [106]:
# add element to Series with pandas version 3
obj = pd.Series(obj.values.tolist() +[4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
7    4
dtype: int64

In [107]:
obj.rank()

0    7.5
1    1.0
2    7.5
3    5.0
4    3.0
5    2.0
6    5.0
7    5.0
dtype: float64

In [114]:
obj.rank(method="first")

0    7.0
1    1.0
2    8.0
3    4.0
4    3.0
5    2.0
6    5.0
7    6.0
dtype: float64

In [115]:
obj.rank(ascending=False)

0    1.5
1    8.0
2    1.5
3    4.0
4    6.0
5    7.0
6    4.0
7    4.0
dtype: float64

In [117]:
obj.rank(ascending=False, method="first")

0    1.0
1    8.0
2    2.0
3    3.0
4    6.0
5    7.0
6    4.0
7    5.0
dtype: float64

In [118]:
obj.rank(method="max")

0    8.0
1    1.0
2    8.0
3    6.0
4    3.0
5    2.0
6    6.0
7    6.0
dtype: float64

In [119]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
7    4
dtype: int64

In [112]:
[type(obj.values.tolist()),type(obj.values),obj.array, obj.to_numpy()]

[list,
 numpy.ndarray,
 <NumpyExtensionArray>
 [7, -5, 7, 4, 2, 0, 4, 4]
 Length: 8, dtype: int64,
 array([ 7, -5,  7,  4,  2,  0,  4,  4], dtype=int64)]

In [109]:
obj.array

<NumpyExtensionArray>
[7, -5, 7, 4, 2, 0, 4, 4]
Length: 8, dtype: int64

In [111]:
obj.values

array([ 7, -5,  7,  4,  2,  0,  4,  4], dtype=int64)

In [113]:
obj.to_numpy()

array([ 7, -5,  7,  4,  2,  0,  4,  4], dtype=int64)

## Axis Indexes with Duplicate Labels

In [120]:
obj.index.is_unique

True

In [125]:
obj4 = obj.reindex(index=[0, 0, 1, 2, 3])
obj4

0    7
0    7
1   -5
2    7
3    4
dtype: int64

In [126]:
obj4.index.is_unique

False

In [127]:
obj4[0]

0    7
0    7
dtype: int64

In [128]:
# dataframe with non unique index
df = pd.DataFrame(np.random.randn(4, 3), index=["a", "a", "b", "b"])
df

0         1         2
a -0.971099 -0.323391 -1.106010
a  0.948376  0.851856 -1.462443
b  2.067112 -1.411396  0.120535
b -1.511658 -1.676119 -2.060295

In [134]:
df.loc["b"]

0         1         2
b  2.067112 -1.411396  0.120535
b -1.511658 -1.676119 -2.060295

# Summarizing and Computing Descriptive Statistics

In [140]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], 
                  index=["a", "b", "c", "d"], 
                  columns=["one", "two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [137]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [138]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [139]:
df.mean(axis="columns", skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

## Correlation and Covariance

In [143]:
price = pd.read_pickle("../examples/yahoo_price.pkl")
price

AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [145]:
volume = pd.read_pickle("../examples/yahoo_volume.pkl")
volume

AAPL      GOOG       IBM      MSFT
Date                                               
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [147]:
returns = price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [148]:
returns["MSFT"].corr(returns["IBM"])

0.4997636114415114

In [150]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [151]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [152]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

## Unique Values, Value Counts, and Membership

In [153]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [161]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [163]:
print(uniques.sort())

None


In [169]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [168]:
obj.value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [165]:
pd.value_counts(obj.values, sort=False)

C:\Users\phil7\AppData\Local\Temp\ipykernel_29964\3084372382.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [171]:
mask = obj.isin(["b", "c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [172]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [173]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [174]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],    
                     "Qu2": [2, 3, 1, 2, 3],    
                     "Qu3": [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [175]:
data["Qu1"].value_counts()

Qu1
3    2
4    2
1    1
Name: count, dtype: int64

In [184]:
data.apply(pd.value_counts).fillna(0)

C:\Users\phil7\AppData\Local\Temp\ipykernel_29964\2493099384.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  data.apply(pd.value_counts).fillna(0)


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0